from __future__ import annotations

from datetime import date
from decimal import Decimal
from urllib.parse import quote


def money(value: int) -> Decimal:
    return Decimal(str(value))


def book_cover(isbn: str) -> str:
    return f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"


def demo_cover(label: str, title: str, background: str) -> str:
    text = quote(f"{label}: {title}", safe="")
    return f"https://placehold.co/600x900/{background}/ffffff.png?text={text}"


def book(
    index: int,
    *,
    title: str,
    authors: str,
    publisher: str,
    publication_date: date,
    pages: int,
    genre: str,
    isbn: str,
    description: str,
    original_value: int,
    current_price: int,
    stock: int,
    category: str | None = None,
) -> dict:
    return {
        "product_type": "BOOK",
        "title": title,
        # Category is the browsable subject/genre, distinct from the medium (product_type).
        "category": category or genre,
        "general_description": description,
        "barcode": f"SEED-BOOK-{index:03d}",
        "image_url": book_cover(isbn),
        "original_value": money(original_value),
        "current_price": money(current_price),
        "weight": Decimal("0.55"),
        "stock_quantity": stock,
        "type_details": {
            "authors": authors,
            "cover_type": "Paperback",
            "publisher": publisher,
            "publication_date": publication_date,
            "pages": pages,
            "language": "English",
            "genre": genre,
        },
    }


def cd(
    index: int,
    *,
    title: str,
    artists: str,
    record_label: str,
    release_date: date,
    genre: str,
    tracks: str,
    description: str,
    original_value: int,
    current_price: int,
    stock: int,
    category: str | None = None,
) -> dict:
    return {
        "product_type": "CD",
        "title": title,
        # Category is the browsable subject/genre, distinct from the medium (product_type).
        "category": category or genre,
        "general_description": description,
        "barcode": f"SEED-CD-{index:03d}",
        "image_url": demo_cover("CD", title, "1f2937"),
        "original_value": money(original_value),
        "current_price": money(current_price),
        "weight": Decimal("0.12"),
        "stock_quantity": stock,
        "type_details": {
            "artists": artists,
            "record_label": record_label,
            "tracklist": tracks,
            "genre": genre,
            "release_date": release_date,
        },
    }


def dvd(
    index: int,
    *,
    title: str,
    director: str,
    studio: str,
    release_date: date,
    runtime: int,
    genre: str,
    description: str,
    original_value: int,
    current_price: int,
    stock: int,
    category: str | None = None,
) -> dict:
    return {
        "product_type": "DVD",
        "title": title,
        # Category is the browsable subject/genre, distinct from the medium (product_type).
        "category": category or genre,
        "general_description": description,
        "barcode": f"SEED-DVD-{index:03d}",
        "image_url": demo_cover("DVD", title, "7f1d1d"),
        "original_value": money(original_value),
        "current_price": money(current_price),
        "weight": Decimal("0.15"),
        "stock_quantity": stock,
        "type_details": {
            "disc_type": "Blu-ray",
            "director": director,
            "runtime_minutes": runtime,
            "studio": studio,
            "language": "English",
            "subtitles": "English",
            "release_date": release_date,
            "genre": genre,
        },
    }


def newspaper(
    index: int,
    *,
    title: str,
    publisher: str,
    editor: str,
    frequency: str,
    issn: str,
    sections: str,
    description: str,
    original_value: int,
    current_price: int,
    stock: int,
    category: str = "News",
) -> dict:
    return {
        "product_type": "NEWSPAPER",
        "title": title,
        # Newspapers have no genre, so default the browsable category to "News" (overridable per item).
        "category": category,
        "general_description": description,
        "barcode": f"SEED-NEWS-{index:03d}",
        "image_url": demo_cover("Newspaper", title, "334155"),
        "original_value": money(original_value),
        "current_price": money(current_price),
        "weight": Decimal("0.20"),
        "stock_quantity": stock,
        "type_details": {
            "publisher": publisher,
            "publication_date": date(2026, 6, 1),
            "issue_number": f"2026-{index:03d}",
            "editor_in_chief": editor,
            "publication_frequency": frequency,
            "issn": issn,
            "language": "English",
            "sections": sections,
        },
    }


DEMO_PRODUCTS = [
    book(
        1,
        title="Domain-Driven Design",
        authors="Eric Evans",
        publisher="Addison-Wesley Professional",
        publication_date=date(2003, 8, 30),
        pages=560,
        genre="Software Engineering",
        isbn="0321125215",
        description="A practical guide to modeling complex business software around a shared domain language.",
        original_value=100000,
        current_price=90000,
        stock=20,
    ),
    book(
        2,
        title="Clean Code",
        authors="Robert C. Martin",
        publisher="Prentice Hall",
        publication_date=date(2008, 8, 1),
        pages=464,
        genre="Software Engineering",
        isbn="0132350882",
        description="Guidance on writing readable, maintainable, production-quality software.",
        original_value=240000,
        current_price=220000,
        stock=18,
    ),
    book(
        3,
        title="The Pragmatic Programmer",
        authors="Andrew Hunt, David Thomas",
        publisher="Addison-Wesley Professional",
        publication_date=date(1999, 10, 30),
        pages=352,
        genre="Software Engineering",
        isbn="020161622X",
        description="A classic collection of practical habits for professional software developers.",
        original_value=260000,
        current_price=235000,
        stock=16,
    ),
    book(
        4,
        title="Design Patterns",
        authors="Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        publisher="Addison-Wesley Professional",
        publication_date=date(1994, 10, 31),
        pages=395,
        genre="Software Engineering",
        isbn="0201633612",
        description="The original catalog of reusable object-oriented design patterns.",
        original_value=280000,
        current_price=260000,
        stock=12,
    ),
    book(
        5,
        title="Refactoring",
        authors="Martin Fowler",
        publisher="Addison-Wesley Professional",
        publication_date=date(2018, 11, 20),
        pages=448,
        genre="Software Engineering",
        isbn="0134757599",
        description="Techniques for improving existing code while preserving behavior.",
        original_value=320000,
        current_price=295000,
        stock=14,
    ),
    book(
        6,
        title="Introduction to Algorithms",
        authors="Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
        publisher="MIT Press",
        publication_date=date(2022, 4, 5),
        pages=1312,
        genre="Computer Science",
        isbn="026204630X",
        description="A comprehensive textbook covering fundamental algorithms and data structures.",
        original_value=650000,
        current_price=610000,
        stock=9,
    ),
    book(
        7,
        title="Artificial Intelligence: A Modern Approach",
        authors="Stuart Russell, Peter Norvig",
        publisher="Pearson",
        publication_date=date(2020, 4, 28),
        pages=1136,
        genre="Artificial Intelligence",
        isbn="0134610997",
        description="A broad university-level introduction to modern artificial intelligence.",
        original_value=620000,
        current_price=585000,
        stock=10,
    ),
    book(
        8,
        title="Deep Learning",
        authors="Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        publisher="MIT Press",
        publication_date=date(2016, 11, 18),
        pages=800,
        genre="Artificial Intelligence",
        isbn="0262035618",
        description="A foundational reference on neural networks and representation learning.",
        original_value=590000,
        current_price=540000,
        stock=11,
    ),
    book(
        9,
        title="The Lean Startup",
        authors="Eric Ries",
        publisher="Crown Business",
        publication_date=date(2011, 9, 13),
        pages=336,
        genre="Business",
        isbn="0307887898",
        description="A methodology for building products through validated learning and rapid iteration.",
        original_value=190000,
        current_price=170000,
        stock=22,
    ),
    book(
        10,
        title="Atomic Habits",
        authors="James Clear",
        publisher="Avery",
        publication_date=date(2018, 10, 16),
        pages=320,
        genre="Self Help",
        isbn="0735211299",
        description="A practical system for improving habits through small, consistent behavior changes.",
        original_value=210000,
        current_price=189000,
        stock=30,
    ),
    book(
        11,
        title="Educated",
        authors="Tara Westover",
        publisher="Random House",
        publication_date=date(2018, 2, 20),
        pages=352,
        genre="Memoir",
        isbn="0399590501",
        description="A memoir about family, isolation, and the life-changing force of education.",
        original_value=230000,
        current_price=205000,
        stock=15,
    ),
    book(
        12,
        title="Sapiens",
        authors="Yuval Noah Harari",
        publisher="Harper",
        publication_date=date(2015, 2, 10),
        pages=464,
        genre="History",
        isbn="0062316095",
        description="A sweeping history of humankind from early Homo sapiens to the modern age.",
        original_value=260000,
        current_price=238000,
        stock=17,
    ),
    book(
        13,
        title="The Hobbit",
        authors="J.R.R. Tolkien",
        publisher="Houghton Mifflin Harcourt",
        publication_date=date(2012, 9, 18),
        pages=300,
        genre="Fantasy",
        isbn="054792822X",
        description="Bilbo Baggins joins a company of dwarves on a journey to the Lonely Mountain.",
        original_value=180000,
        current_price=165000,
        stock=25,
    ),
    book(
        14,
        title="Harry Potter and the Sorcerer's Stone",
        authors="J.K. Rowling",
        publisher="Scholastic",
        publication_date=date(1998, 9, 1),
        pages=309,
        genre="Fantasy",
        isbn="059035342X",
        description="The first school year of Harry Potter at Hogwarts School of Witchcraft and Wizardry.",
        original_value=200000,
        current_price=185000,
        stock=26,
    ),
    book(
        15,
        title="To Kill a Mockingbird",
        authors="Harper Lee",
        publisher="Harper Perennial Modern Classics",
        publication_date=date(2006, 5, 23),
        pages=336,
        genre="Fiction",
        isbn="0061120081",
        description="A landmark novel about justice, childhood, and moral courage in the American South.",
        original_value=175000,
        current_price=158000,
        stock=19,
    ),
    cd(
        1,
        title="The Dark Side of the Moon",
        artists="Pink Floyd",
        record_label="Harvest Records",
        release_date=date(1973, 3, 1),
        genre="Progressive Rock",
        tracks="Speak to Me; Breathe; Time; Money; Us and Them; Eclipse",
        description="Pink Floyd's landmark studio album known for its continuous flow and studio craft.",
        original_value=220000,
        current_price=210000,
        stock=15,
    ),
    cd(
        2,
        title="Abbey Road",
        artists="The Beatles",
        record_label="Apple Records",
        release_date=date(1969, 9, 26),
        genre="Rock",
        tracks="Come Together; Something; Here Comes the Sun; Golden Slumbers",
        description="The Beatles' late-period classic featuring the famous second-side medley.",
        original_value=230000,
        current_price=215000,
        stock=14,
    ),
    cd(
        3,
        title="Thriller",
        artists="Michael Jackson",
        record_label="Epic Records",
        release_date=date(1982, 11, 30),
        genre="Pop",
        tracks="Wanna Be Startin' Somethin'; Beat It; Billie Jean; Thriller",
        description="One of the best-selling pop albums of all time, produced by Quincy Jones.",
        original_value=240000,
        current_price=225000,
        stock=20,
    ),
    cd(
        4,
        title="Back in Black",
        artists="AC/DC",
        record_label="Atlantic Records",
        release_date=date(1980, 7, 25),
        genre="Hard Rock",
        tracks="Hells Bells; Shoot to Thrill; Back in Black; You Shook Me All Night Long",
        description="AC/DC's hard rock staple and first album with vocalist Brian Johnson.",
        original_value=210000,
        current_price=199000,
        stock=13,
    ),
    cd(
        5,
        title="Rumours",
        artists="Fleetwood Mac",
        record_label="Warner Bros. Records",
        release_date=date(1977, 2, 4),
        genre="Pop Rock",
        tracks="Dreams; Don't Stop; Go Your Own Way; The Chain",
        description="Fleetwood Mac's polished pop-rock album shaped by personal tension in the band.",
        original_value=220000,
        current_price=205000,
        stock=17,
    ),
    cd(
        6,
        title="Kind of Blue",
        artists="Miles Davis",
        record_label="Columbia Records",
        release_date=date(1959, 8, 17),
        genre="Jazz",
        tracks="So What; Freddie Freeloader; Blue in Green; All Blues; Flamenco Sketches",
        description="A modal jazz masterpiece featuring John Coltrane, Cannonball Adderley, and Bill Evans.",
        original_value=230000,
        current_price=218000,
        stock=12,
    ),
    cd(
        7,
        title="Nevermind",
        artists="Nirvana",
        record_label="DGC Records",
        release_date=date(1991, 9, 24),
        genre="Grunge",
        tracks="Smells Like Teen Spirit; Come as You Are; Lithium; In Bloom",
        description="The breakthrough grunge album that brought Nirvana to global mainstream attention.",
        original_value=210000,
        current_price=198000,
        stock=18,
    ),
    cd(
        8,
        title="The Joshua Tree",
        artists="U2",
        record_label="Island Records",
        release_date=date(1987, 3, 9),
        genre="Rock",
        tracks="Where the Streets Have No Name; I Still Haven't Found What I'm Looking For; With or Without You",
        description="U2's cinematic rock album inspired by American landscapes and spiritual longing.",
        original_value=215000,
        current_price=199000,
        stock=11,
    ),
    cd(
        9,
        title="OK Computer",
        artists="Radiohead",
        record_label="Parlophone",
        release_date=date(1997, 5, 21),
        genre="Alternative Rock",
        tracks="Airbag; Paranoid Android; Karma Police; No Surprises",
        description="Radiohead's acclaimed album about technology, alienation, and modern unease.",
        original_value=235000,
        current_price=220000,
        stock=16,
    ),
    cd(
        10,
        title="1989",
        artists="Taylor Swift",
        record_label="Big Machine Records",
        release_date=date(2014, 10, 27),
        genre="Pop",
        tracks="Blank Space; Style; Shake It Off; Wildest Dreams",
        description="Taylor Swift's synth-pop album marking a full transition from country-pop to pop.",
        original_value=260000,
        current_price=240000,
        stock=24,
    ),
    cd(
        11,
        title="Random Access Memories",
        artists="Daft Punk",
        record_label="Columbia Records",
        release_date=date(2013, 5, 17),
        genre="Electronic",
        tracks="Give Life Back to Music; Instant Crush; Get Lucky; Contact",
        description="Daft Punk's analog-driven electronic album featuring Nile Rodgers and Pharrell Williams.",
        original_value=250000,
        current_price=235000,
        stock=12,
    ),
    cd(
        12,
        title="Blue Train",
        artists="John Coltrane",
        record_label="Blue Note Records",
        release_date=date(1958, 1, 1),
        genre="Jazz",
        tracks="Blue Train; Moment's Notice; Locomotion; Lazy Bird",
        description="A hard bop classic led by saxophonist John Coltrane for Blue Note.",
        original_value=220000,
        current_price=208000,
        stock=9,
    ),
    cd(
        13,
        title="Lemonade",
        artists="Beyonce",
        record_label="Parkwood Entertainment",
        release_date=date(2016, 4, 23),
        genre="R&B",
        tracks="Hold Up; Sorry; 6 Inch; Formation",
        description="A visual-album era release blending R&B, rock, country, and personal storytelling.",
        original_value=270000,
        current_price=249000,
        stock=19,
    ),
    cd(
        14,
        title="To Pimp a Butterfly",
        artists="Kendrick Lamar",
        record_label="Top Dawg Entertainment",
        release_date=date(2015, 3, 15),
        genre="Hip-Hop",
        tracks="King Kunta; Alright; These Walls; The Blacker the Berry",
        description="Kendrick Lamar's jazz and funk-influenced album about identity, fame, and America.",
        original_value=255000,
        current_price=239000,
        stock=14,
    ),
    cd(
        15,
        title="Come Away with Me",
        artists="Norah Jones",
        record_label="Blue Note Records",
        release_date=date(2002, 2, 26),
        genre="Vocal Jazz",
        tracks="Don't Know Why; Come Away with Me; Turn Me On; The Nearness of You",
        description="Norah Jones' warm debut album combining jazz, folk, and country influences.",
        original_value=205000,
        current_price=190000,
        stock=16,
    ),
    dvd(
        1,
        title="Inception",
        director="Christopher Nolan",
        studio="Warner Bros. Pictures",
        release_date=date(2010, 7, 16),
        runtime=148,
        genre="Science Fiction",
        description="A mind-bending heist film built around dreams, memory, and layered realities.",
        original_value=150000,
        current_price=140000,
        stock=10,
    ),
    dvd(
        2,
        title="The Matrix",
        director="Lana Wachowski, Lilly Wachowski",
        studio="Warner Bros. Pictures",
        release_date=date(1999, 3, 31),
        runtime=136,
        genre="Science Fiction",
        description="A cyberpunk action film about simulated reality and human resistance.",
        original_value=165000,
        current_price=150000,
        stock=15,
    ),
    dvd(
        3,
        title="The Lord of the Rings: The Fellowship of the Ring",
        director="Peter Jackson",
        studio="New Line Cinema",
        release_date=date(2001, 12, 19),
        runtime=178,
        genre="Fantasy",
        description="The first chapter of Peter Jackson's adaptation of J.R.R. Tolkien's fantasy epic.",
        original_value=190000,
        current_price=175000,
        stock=12,
    ),
    dvd(
        4,
        title="Spirited Away",
        director="Hayao Miyazaki",
        studio="Studio Ghibli",
        release_date=date(2001, 7, 20),
        runtime=125,
        genre="Animation",
        description="A Studio Ghibli animated feature about a girl navigating a mysterious spirit world.",
        original_value=180000,
        current_price=168000,
        stock=14,
    ),
    dvd(
        5,
        title="Parasite",
        director="Bong Joon Ho",
        studio="CJ Entertainment",
        release_date=date(2019, 5, 30),
        runtime=132,
        genre="Thriller",
        description="A dark social thriller about class conflict, deception, and family survival.",
        original_value=175000,
        current_price=160000,
        stock=13,
    ),
    dvd(
        6,
        title="The Godfather",
        director="Francis Ford Coppola",
        studio="Paramount Pictures",
        release_date=date(1972, 3, 24),
        runtime=175,
        genre="Crime",
        description="A landmark crime drama following the Corleone family and the transfer of power.",
        original_value=180000,
        current_price=165000,
        stock=11,
    ),
    dvd(
        7,
        title="The Shawshank Redemption",
        director="Frank Darabont",
        studio="Castle Rock Entertainment",
        release_date=date(1994, 9, 23),
        runtime=142,
        genre="Drama",
        description="A prison drama about hope, friendship, and resilience over decades.",
        original_value=160000,
        current_price=148000,
        stock=18,
    ),
    dvd(
        8,
        title="Interstellar",
        director="Christopher Nolan",
        studio="Paramount Pictures",
        release_date=date(2014, 11, 7),
        runtime=169,
        genre="Science Fiction",
        description="An ambitious space epic about survival, time dilation, and human connection.",
        original_value=185000,
        current_price=172000,
        stock=17,
    ),
    dvd(
        9,
        title="The Dark Knight",
        director="Christopher Nolan",
        studio="Warner Bros. Pictures",
        release_date=date(2008, 7, 18),
        runtime=152,
        genre="Action",
        description="A crime-action superhero film centered on Batman, the Joker, and Gotham's moral crisis.",
        original_value=175000,
        current_price=158000,
        stock=16,
    ),
    dvd(
        10,
        title="Pulp Fiction",
        director="Quentin Tarantino",
        studio="Miramax",
        release_date=date(1994, 10, 14),
        runtime=154,
        genre="Crime",
        description="A nonlinear crime film known for sharp dialogue, intersecting stories, and pop culture style.",
        original_value=165000,
        current_price=150000,
        stock=10,
    ),
    dvd(
        11,
        title="Forrest Gump",
        director="Robert Zemeckis",
        studio="Paramount Pictures",
        release_date=date(1994, 7, 6),
        runtime=142,
        genre="Drama",
        description="A decades-spanning American story following Forrest Gump through historic events.",
        original_value=155000,
        current_price=145000,
        stock=20,
    ),
    dvd(
        12,
        title="Jurassic Park",
        director="Steven Spielberg",
        studio="Universal Pictures",
        release_date=date(1993, 6, 11),
        runtime=127,
        genre="Adventure",
        description="A dinosaur theme park adventure that became a benchmark for visual effects.",
        original_value=170000,
        current_price=155000,
        stock=18,
    ),
    dvd(
        13,
        title="Toy Story",
        director="John Lasseter",
        studio="Pixar Animation Studios",
        release_date=date(1995, 11, 22),
        runtime=81,
        genre="Animation",
        description="Pixar's first feature film, following toys that come alive when people are away.",
        original_value=150000,
        current_price=138000,
        stock=22,
    ),
    dvd(
        14,
        title="Titanic",
        director="James Cameron",
        studio="20th Century Fox",
        release_date=date(1997, 12, 19),
        runtime=195,
        genre="Romance",
        description="A historical romance and disaster film set aboard the RMS Titanic.",
        original_value=165000,
        current_price=152000,
        stock=14,
    ),
    dvd(
        15,
        title="La La Land",
        director="Damien Chazelle",
        studio="Summit Entertainment",
        release_date=date(2016, 12, 9),
        runtime=128,
        genre="Musical",
        description="A modern musical about ambition, love, and artistic compromise in Los Angeles.",
        original_value=160000,
        current_price=148000,
        stock=12,
    ),
    newspaper(
        1,
        title="The New York Times",
        publisher="The New York Times Company",
        editor="Joseph Kahn",
        frequency="Daily",
        issn="0362-4331",
        sections="World, U.S., Business, Arts, Science, Sports, Opinion",
        description="A daily U.S. newspaper known for international reporting and investigative journalism.",
        original_value=45000,
        current_price=39000,
        stock=80,
    ),
    newspaper(
        2,
        title="The Washington Post",
        publisher="WP Company LLC",
        editor="Matt Murray",
        frequency="Daily",
        issn="0190-8286",
        sections="Politics, World, Business, Technology, Sports, Opinion",
        description="A major U.S. newspaper with strong coverage of politics and national affairs.",
        original_value=42000,
        current_price=38000,
        stock=72,
    ),
    newspaper(
        3,
        title="The Wall Street Journal",
        publisher="Dow Jones & Company",
        editor="Emma Tucker",
        frequency="Daily",
        issn="0099-9660",
        sections="Markets, Business, Economy, Technology, Opinion, Lifestyle",
        description="A leading business newspaper focused on finance, markets, and global commerce.",
        original_value=50000,
        current_price=46000,
        stock=65,
    ),
    newspaper(
        4,
        title="Financial Times",
        publisher="The Financial Times Ltd",
        editor="Roula Khalaf",
        frequency="Daily",
        issn="0307-1766",
        sections="Companies, Markets, Global Economy, Opinion, Work and Careers",
        description="An international business newspaper recognized for global financial reporting.",
        original_value=52000,
        current_price=48000,
        stock=54,
    ),
    newspaper(
        5,
        title="The Guardian Weekly",
        publisher="Guardian News and Media",
        editor="Graham Snowdon",
        frequency="Weekly",
        issn="0959-3608",
        sections="World, Environment, Culture, Opinion, Review",
        description="A weekly international edition collecting reporting and commentary from The Guardian.",
        original_value=48000,
        current_price=44000,
        stock=50,
    ),
    newspaper(
        6,
        title="USA Today",
        publisher="Gannett",
        editor="Terence Samuel",
        frequency="Daily",
        issn="0734-7456",
        sections="News, Money, Sports, Life, Travel, Opinion",
        description="A national U.S. newspaper known for concise reporting and broad daily coverage.",
        original_value=36000,
        current_price=32000,
        stock=90,
    ),
    newspaper(
        7,
        title="Los Angeles Times",
        publisher="Los Angeles Times Communications",
        editor="Terry Tang",
        frequency="Daily",
        issn="0458-3035",
        sections="California, Entertainment, Sports, Food, Opinion, World",
        description="A major U.S. West Coast newspaper with strong culture and California coverage.",
        original_value=39000,
        current_price=35000,
        stock=68,
    ),
    newspaper(
        8,
        title="Chicago Tribune",
        publisher="Tribune Publishing",
        editor="Mitch Pugh",
        frequency="Daily",
        issn="1085-6706",
        sections="News, Business, Sports, Food, Opinion, Arts",
        description="A long-running daily newspaper serving Chicago and the Midwest.",
        original_value=35000,
        current_price=31000,
        stock=60,
    ),
    newspaper(
        9,
        title="The Times",
        publisher="Times Media Limited",
        editor="Tony Gallagher",
        frequency="Daily",
        issn="0140-0460",
        sections="News, Comment, Business, Sport, Register, Arts",
        description="A British daily newspaper with national, political, business, and cultural coverage.",
        original_value=44000,
        current_price=40000,
        stock=56,
    ),
    newspaper(
        10,
        title="Le Monde",
        publisher="Societe Editrice du Monde",
        editor="Jerome Fenoglio",
        frequency="Daily",
        issn="0395-2037",
        sections="International, France, Economy, Culture, Ideas, Sport",
        description="A major French daily newspaper known for analysis of politics and global affairs.",
        original_value=43000,
        current_price=39000,
        stock=52,
    ),
    newspaper(
        11,
        title="The Japan Times",
        publisher="The Japan Times, Ltd.",
        editor="Hiroyasu Mizuno",
        frequency="Daily",
        issn="0447-5763",
        sections="Japan, World, Business, Culture, Sports, Opinion",
        description="An English-language newspaper covering Japan, Asia, business, and culture.",
        original_value=41000,
        current_price=37000,
        stock=64,
    ),
    newspaper(
        12,
        title="The Straits Times",
        publisher="SPH Media",
        editor="Jaime Ho",
        frequency="Daily",
        issn="0585-3923",
        sections="Singapore, Asia, World, Business, Sport, Life",
        description="A leading Singapore newspaper with extensive Southeast Asia coverage.",
        original_value=38000,
        current_price=34000,
        stock=70,
    ),
    newspaper(
        13,
        title="The Australian",
        publisher="News Corp Australia",
        editor="Michelle Gunn",
        frequency="Daily",
        issn="1038-8761",
        sections="Nation, World, Business, Sport, Arts, Opinion",
        description="A national Australian newspaper covering politics, business, and public affairs.",
        original_value=40000,
        current_price=36000,
        stock=58,
    ),
    newspaper(
        14,
        title="Tuoi Tre Daily",
        publisher="Tuoi Tre Newspaper",
        editor="Le The Chu",
        frequency="Daily",
        issn="0868-2828",
        sections="News, Youth, Business, Education, Sports, Culture",
        description="A major Vietnamese daily newspaper covering national news, society, and youth issues.",
        original_value=15000,
        current_price=12000,
        stock=120,
    ),
    newspaper(
        15,
        title="Thanh Nien Daily",
        publisher="Vietnam Youth Federation",
        editor="Nguyen Ngoc Toan",
        frequency="Daily",
        issn="1859-1221",
        sections="News, Politics, Business, Education, Sports, Entertainment",
        description="A Vietnamese daily newspaper with broad coverage of news, society, and lifestyle.",
        original_value=15000,
        current_price=12000,
        stock=110,
    ),
]
