# Generated by Django 5.2.14 on 2026-05-29 13:57

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_newspaper_editor_in_chief_newspaper_issn_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliveryinfo',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_fee__gte', 0)), name='ck_delivery_infos_shipping_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_product_price_excl_vat__gte', 0), ('vat_amount__gte', 0), ('total_product_price_incl_vat__gte', 0), ('delivery_fee__gte', 0), ('total_amount_to_pay__gte', 0)), name='ck_invoices_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_product_price_incl_vat', django.db.models.expressions.CombinedExpression(models.F('total_product_price_excl_vat'), '+', models.F('vat_amount')))), name='ck_invoices_total_product_incl_formula'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_to_pay', django.db.models.expressions.CombinedExpression(models.F('total_product_price_incl_vat'), '+', models.F('delivery_fee')))), name='ck_invoices_total_amount_formula'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_order_items_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_order_items_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_amount_excl_vat__gte', 0), ('line_amount_incl_vat__gte', 0)), name='ck_order_items_line_amounts_non_negative'),
        ),
    ]
