# Generated by Django 5.2.14 on 2026-05-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryinfo_ck_delivery_infos_shipping_fee_non_negative_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved/rejected the order (set during order processing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='users.user'),
        ),
    ]
