apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aims-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jayyyyte/ISD.20252-18
    targetRevision: main
    path: Programming/k8s/aims-chart
    helm:
      releaseName: aims
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
