controller:
  nodeSelector:
    aims.io/node-pool: system
    kubernetes.io/os: linux

dashboard:
  enabled: true
  nodeSelector:
    aims.io/node-pool: system
    kubernetes.io/os: linux
  service:
    type: NodePort
    nodePort: 30100
