initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      credential:
        name: cloud-credentials
        key: cloud
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://minio.production.svc.cluster.local
  volumeSnapshotLocation: []
  defaultVolumesToFsBackup: true

credentials:
  useSecret: true
  existingSecret: cloud-credentials

snapshotsEnabled: false
deployNodeAgent: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeAgent:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
