VIETNAM_PROVINCES = (
    "An Giang",
    "Ba Ria - Vung Tau",
    "Bac Giang",
    "Bac Kan",
    "Bac Lieu",
    "Bac Ninh",
    "Ben Tre",
    "Binh Dinh",
    "Binh Duong",
    "Binh Phuoc",
    "Binh Thuan",
    "Ca Mau",
    "Can Tho",
    "Cao Bang",
    "Da Nang",
    "Dak Lak",
    "Dak Nong",
    "Dien Bien",
    "Dong Nai",
    "Dong Thap",
    "Gia Lai",
    "Ha Giang",
    "Ha Nam",
    "Ha Noi",
    "Ha Tinh",
    "Hai Duong",
    "Hai Phong",
    "Hau Giang",
    "Hoa Binh",
    "Hung Yen",
    "Khanh Hoa",
    "Kien Giang",
    "Kon Tum",
    "Lai Chau",
    "Lam Dong",
    "Lang Son",
    "Lao Cai",
    "Long An",
    "Nam Dinh",
    "Nghe An",
    "Ninh Binh",
    "Ninh Thuan",
    "Phu Tho",
    "Phu Yen",
    "Quang Binh",
    "Quang Nam",
    "Quang Ngai",
    "Quang Ninh",
    "Quang Tri",
    "Soc Trang",
    "Son La",
    "Tay Ninh",
    "Thai Binh",
    "Thai Nguyen",
    "Thanh Hoa",
    "Thua Thien Hue",
    "Tien Giang",
    "Tra Vinh",
    "Tuyen Quang",
    "Vinh Long",
    "Vinh Phuc",
    "Yen Bai",
    "Ho Chi Minh City",
)

PROVINCE_TO_REGION = {
    "Ha Giang": "NORTH",
    "Cao Bang": "NORTH",
    "Bac Kan": "NORTH",
    "Tuyen Quang": "NORTH",
    "Lao Cai": "NORTH",
    "Yen Bai": "NORTH",
    "Thai Nguyen": "NORTH",
    "Lang Son": "NORTH",
    "Quang Ninh": "NORTH",
    "Bac Giang": "NORTH",
    "Phu Tho": "NORTH",
    "Vinh Phuc": "NORTH",
    "Bac Ninh": "NORTH",
    "Hai Duong": "NORTH",
    "Hai Phong": "NORTH",
    "Hung Yen": "NORTH",
    "Thai Binh": "NORTH",
    "Ha Nam": "NORTH",
    "Nam Dinh": "NORTH",
    "Ninh Binh": "NORTH",
    "Ha Noi": "NORTH",
    "Hoa Binh": "NORTH",
    "Son La": "NORTH",
    "Dien Bien": "NORTH",
    "Lai Chau": "NORTH",
    "Thanh Hoa": "CENTRAL",
    "Nghe An": "CENTRAL",
    "Ha Tinh": "CENTRAL",
    "Quang Binh": "CENTRAL",
    "Quang Tri": "CENTRAL",
    "Thua Thien Hue": "CENTRAL",
    "Da Nang": "CENTRAL",
    "Quang Nam": "CENTRAL",
    "Quang Ngai": "CENTRAL",
    "Binh Dinh": "CENTRAL",
    "Phu Yen": "CENTRAL",
    "Khanh Hoa": "CENTRAL",
    "Ninh Thuan": "CENTRAL",
    "Binh Thuan": "CENTRAL",
    "Kon Tum": "CENTRAL",
    "Gia Lai": "CENTRAL",
    "Dak Lak": "CENTRAL",
    "Dak Nong": "CENTRAL",
    "Lam Dong": "CENTRAL",
    "Binh Phuoc": "SOUTH",
    "Tay Ninh": "SOUTH",
    "Binh Duong": "SOUTH",
    "Dong Nai": "SOUTH",
    "Ba Ria - Vung Tau": "SOUTH",
    "Ho Chi Minh City": "SOUTH",
    "Long An": "SOUTH",
    "Tien Giang": "SOUTH",
    "Ben Tre": "SOUTH",
    "Tra Vinh": "SOUTH",
    "Vinh Long": "SOUTH",
    "Dong Thap": "SOUTH",
    "An Giang": "SOUTH",
    "Kien Giang": "SOUTH",
    "Can Tho": "SOUTH",
    "Hau Giang": "SOUTH",
    "Soc Trang": "SOUTH",
    "Bac Lieu": "SOUTH",
    "Ca Mau": "SOUTH",
}

VIETNAM_PROVINCE_SET = frozenset(VIETNAM_PROVINCES)


def normalize_province(province: str | None) -> str:
    if province is None:
        return ""
    return province.strip()


def resolve_region(province: str | None) -> str:
    normalized = normalize_province(province)
    if not normalized:
        raise ValueError("province must not be empty")
    if normalized not in VIETNAM_PROVINCE_SET:
        raise ValueError("province must be one of the supported Vietnam provinces/cities")
    return PROVINCE_TO_REGION[normalized]
