# Generated by Django 5.2.14 on 2026-05-29 13:57

import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='editor_in_chief',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='issn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='language',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='publication_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='sections',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_value',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('height__gte', 0), ('width__gte', 0), ('length__gte', 0), ('weight__gte', 0)), name='ck_products_dimensions_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('original_value__gte', 0), ('current_price__gte', 0)), name='ck_products_values_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__gte', django.db.models.expressions.CombinedExpression(models.F('original_value'), '*', models.Value(Decimal('0.30'))))), name='ck_products_price_lower_bound'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__lte', django.db.models.expressions.CombinedExpression(models.F('original_value'), '*', models.Value(Decimal('1.50'))))), name='ck_products_price_upper_bound'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DELETED'), _negated=True), ('stock_quantity', 0), _connector='OR'), name='ck_products_deleted_only_when_stock_zero'),
        ),
    ]
