# Generated by Django 5.2.14 on 2026-05-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newspaper_editor_in_chief_newspaper_issn_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Manager/admin who performed the action. Always set by ProductHistoryService.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_histories', to='users.user'),
        ),
    ]
