# Generated by Django 5.2.14 on 2026-05-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_deliveryinfo_ck_delivery_infos_shipping_fee_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('PAYPAL', 'PayPal'), ('VIETQR', 'VietQR')], max_length=20)),
                ('provider_order_id', models.CharField(blank=True, help_text='The order/payment ID returned by the payment provider (e.g. PayPal order ID).', max_length=128)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, help_text='Provider-side reference used to match callbacks (e.g. VietQR content code). Blank for PayPal.', max_length=64)),
                ('provider_payload', models.JSONField(blank=True, default=dict, help_text='Provider-specific extra data (e.g. VietQR qr_payload/qr_image_url). Gateway-agnostic JSON.')),
                ('capture_id', models.CharField(blank=True, help_text='The capture ID returned after a successful payment capture. Used for refunds.', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('refund_id', models.CharField(blank=True, help_text='The refund ID from the payment provider after a successful refund.', max_length=128)),
                ('transaction_content', models.TextField(blank=True, help_text='Human-readable payment content/description (e.g. VietQR transfer content).')),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(help_text='The AIMS order this payment settles.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'ordering': ['-transaction_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund_reason', models.TextField()),
                ('refund_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('MANUAL_REQUIRED', 'Manual required')], default='PENDING', max_length=20)),
                ('refund_method', models.CharField(choices=[('PAYPAL_API', 'PayPal API'), ('MANUAL_BANK_TRANSFER', 'Manual bank transfer')], max_length=24)),
                ('manual_refund_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_payment_transactions_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refundtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='ck_refund_transactions_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refundtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('refund_method', 'MANUAL_BANK_TRANSFER'), _negated=True), models.Q(('manual_refund_note', ''), _negated=True), _connector='OR'), name='ck_refund_transactions_manual_note_required'),
        ),
    ]
