# Generated by Django 5.2.14 on 2026-06-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0003_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundtransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Manager who confirmed the manual refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to='users.user'),
        ),
    ]
