# Generated by Django 5.2.14 on 2026-05-30 12:28

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 30, 12, 28, 33, 779292, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User created'), ('USER_STATUS_CHANGED', 'User status changed'), ('USER_ROLES_CHANGED', 'User roles changed'), ('USER_PROFILE_UPDATED', 'User profile updated'), ('USER_EMAIL_CHANGED', 'User email changed'), ('PASSWORD_RESET', 'Password reset (admin)'), ('PASSWORD_CHANGED', 'Password changed (self)'), ('ROLE_CREATED', 'Role created')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='users.user')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
